name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1]

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup ssh agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      run: |
        sh -c "rsync -avh $GITHUB_WORKSPACE/src/ $DEPLOY_DESTINATION"
      env:
        DEPLOY_DESTINATION: ${{ secrets.DEPLOY_DESTINATION }}


#                sh -c "ls $GITHUB_WORKSPACE"



#    - name: Testing script 3
#      run: sh -c "${DEPLOY_SCRIPT}"
#      env:
#        DEPLOY_SCRIPT: ${{ secrets.DEPLOY_SCRIPT }}

#    - name: Update Coverage Badge json on gist
#      uses: schneegans/dynamic-badges-action@v1.2.0
#      with:
#        auth: ${{ secrets.GIST_SECRET }}
#        gistID: 91b667a55d12e70f688f7786fa693069
#        filename: coverage-badge-image-mime-type-sniffer.json
#        label: Hellllo
#        message: From GA
#        color: orange


    #- name: Generate test coverage badge
    #  uses: timkrase/phpunit-coverage-badge@v1.2.0
    #  with:
    #    report: build/coverage.clover
    #    report_type: clover
    #    coverage_badge_path: 'badge-coverage.svg'
    #    push_badge: true
    #    repo_token: ${{ secrets.GITHUB_TOKEN }}
    #    commit_message: Update code coverage badge [ci]
    #    commit_email: it@rosell.dk
    #    commit_name: Bjørn Rosell
