name: Large testsuite (run manually before releases)

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        #os: [ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019, macos-11, macos-10.15]
        os: [ubuntu-20.04]
        #php: [8.1, 8.0, 7.4, 7.3, 7.2, 7.1, 7.0]
        php: [8.1, 7.3]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        #extensions: exif, mbstring, fileinfo

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php${{ matrix.php }}-

    - name: Downgrade phpunit to a version that supports PHP 7.2
      if: matrix.php == '7.2'
      run: composer require "phpunit/phpunit:^8.0" --dev

    - name: Downgrade phpunit to a version that supports PHP 7.1
      if: matrix.php == '7.1'
      run: composer require "phpunit/phpunit:^7.0" --dev

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test
