name: Large testsuite (run manually before releases)

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019, macos-11, macos-10.15]
        #os: [ubuntu-20.04]
        php: [8.1, 8.0, 7.4, 7.3, 7.2, 7.1, 7.0]
        #php: [8.1, 7.3]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        #extensions: exif, mbstring, fileinfo

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php${{ matrix.php }}-

    - name: PHP 7.2 alterations for composer
      # Downgrade phpunit to v8, which is the highest version that supports PHP 7.2
      if: matrix.php == '7.2'
      run: composer require "phpunit/phpunit:^8.0" --dev --no-update

    - name: PHP 7.1 alterations for composer
      # 1. Remove phpstan, as it does not work on PHP 7.1
      # 2: Downgrade phpunit to v7, which is the highest version that supports PHP 7.1
      if: matrix.php == '7.1'
      run: |
        composer remove phpstan/phpstan --dev --no-update
        composer require "phpunit/phpunit:^7.0" --dev --no-update
        composer update

    - name: PHP 7.0 alterations for composer
      # 1. Remove phpstan, as it does not work on PHP 7.0
      # 2: Downgrade phpunit to v6, which is the highest version that supports PHP 7.0
      if: matrix.php == '7.0'
      run: |
        composer remove phpstan/phpstan --dev --no-update
        composer require "phpunit/phpunit:^6.0" --dev --no-update
        composer update

    - name: Run phpunit (test cases)
      run: composer run-script test-no-cov

    - name: Run phpstan on PHP>=7.2 (to check php syntax)
      if: (matrix.php != '7.0') && (matrix.php != '7.1') && (matrix.php != '7.2')
      run: composer run-script phpstan

    - name: run phpcs (to check coding style)
      run: composer run-script phpcs-all
